# Generated by Django 3.2.7 on 2021-10-06 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='First name')),
                ('surname', models.CharField(max_length=50, verbose_name='Last name')),
                ('phone', models.CharField(max_length=12, verbose_name='User phone number')),
                ('address', models.CharField(max_length=255, verbose_name='User address')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Product name')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name deal')),
                ('description', models.TextField(verbose_name='Description')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Delivery address')),
                ('delivery_date', models.CharField(max_length=20, verbose_name='Delivery date')),
                ('delivery_code', models.CharField(max_length=50, verbose_name='Delivery code')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='api.client', verbose_name='Client')),
                ('products', models.ManyToManyField(related_name='product_order', to='api.Product', verbose_name='products')),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
            },
        ),
    ]
