# Generated by Django 3.2.7 on 2021-10-06 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, help_text='Сумма в долларах', max_digits=11, verbose_name='Сумма товара')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение товара')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Количество товара')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Время обновления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='first name')),
                ('surname', models.CharField(max_length=255, verbose_name='last name')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name="Buyer's phone number")),
                ('address', models.CharField(max_length=255, verbose_name="Buyer's address")),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Product Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Delivery address')),
                ('delivery_date', models.CharField(max_length=20, verbose_name='Delivery date')),
                ('delivery_code', models.CharField(max_length=50, verbose_name='Delivery code')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='api.user', verbose_name='User')),
                ('product', models.ManyToManyField(related_name='product_order', to='api.Product', verbose_name='products')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
    ]
